-- Mentoria Hub — sample catalog seed for the production Supabase schema.
-- Run after schema.sql. Mirrors the in-app demo catalog so a freshly wired
-- Supabase backend shows the same realistic data.

insert into opportunities (title, organizer, category, direction, format, deadline, description, requirements, apply_url, grade_min, grade_max, tags) values
('National Mathematics Olympiad', 'Republican Olympiad Committee', 'Olympiad', 'STEM', 'In-person', current_date + 6, 'The flagship national olympiad in mathematics for secondary school students.', 'Grades 9-11. Strong algebra and geometry.', 'https://example.org/apply/math-olympiad', 9, 11, '{math,olympiad,stem,competition,scholarship}'),
('Junior Business Case Competition', 'Mentoria Partners', 'Competition', 'Business', 'Hybrid', current_date + 12, 'Teams solve a real startup case and pitch to founders and investors.', 'Grades 9-12. Teams of 2-4.', 'https://example.org/apply/biz-case', 9, 12, '{business,startup,pitch,finance,competition}'),
('STEM Summer School Abroad', 'Global Science Foundation', 'Summer School', 'STEM', 'In-person', current_date + 28, 'A two-week residential program covering physics, robotics and applied math.', 'Grades 10-11. Motivation letter.', 'https://example.org/apply/stem-summer', 10, 11, '{stem,physics,robotics,summer,research}'),
('Future Leaders Scholarship', 'Mentoria Foundation', 'Scholarship', 'Social Impact', 'Online', current_date + 18, 'A merit-and-need scholarship covering tuition for online courses and exam fees.', 'Grades 9-12. Essay on a community project.', 'https://example.org/apply/scholarship', 9, 12, '{scholarship,leadership,community,essay}'),
('TeenHack Coding Hackathon', 'DevKids Community', 'Hackathon', 'Coding', 'Hybrid', current_date + 9, 'A 48-hour hackathon where students build apps that solve a local problem.', 'Grades 8-12. Beginners welcome.', 'https://example.org/apply/teenhack', 8, 12, '{coding,hackathon,web,apps,programming}'),
('Young Researchers Program', 'Academy of Sciences', 'Research', 'Science', 'Online', current_date + 35, 'Pairs students with a scientist mentor to complete a small research project.', 'Grades 10-12. Interest in biology, chemistry or physics.', 'https://example.org/apply/young-researchers', 10, 12, '{research,science,biology,mentorship}'),
('Financial Literacy Challenge', 'FinFuture', 'Competition', 'Finance', 'Online', current_date + 15, 'An online competition testing budgeting, investing and economics knowledge.', 'Grades 9-12. No prior finance experience needed.', 'https://example.org/apply/fin-challenge', 9, 12, '{finance,economics,investing,competition}'),
('Eco Volunteering Initiative', 'GreenSteppe NGO', 'Volunteering', 'Social Impact', 'In-person', current_date + 40, 'Join local environmental projects and earn a volunteering certificate.', 'Grades 8-12. Weekend availability.', 'https://example.org/apply/eco-volunteer', 8, 12, '{volunteering,environment,community,certificate}'),
('Tech Startup Internship', 'Mentoria Partners', 'Internship', 'Coding', 'Hybrid', current_date + 22, 'A part-time internship at a local tech startup shadowing engineers.', 'Grades 11-12. Familiarity with one programming language.', 'https://example.org/apply/startup-internship', 11, 12, '{internship,coding,startup,career}'),
('International Debate Tournament', 'Speak Up League', 'Competition', 'Social Impact', 'Online', current_date + 11, 'A British Parliamentary debate tournament building public speaking skills.', 'Grades 9-12. Upper-intermediate English.', 'https://example.org/apply/debate', 9, 12, '{debate,english,public speaking,competition}'),
('SAT Bootcamp Scholarship', 'Mentoria Foundation', 'Scholarship', 'STEM', 'Online', current_date + 4, 'Free seats in an intensive SAT preparation bootcamp.', 'Grades 10-12. Diagnostic test required.', 'https://example.org/apply/sat-bootcamp', 10, 12, '{sat,test prep,university,scholarship}'),
('Biology Knowledge Olympiad', 'Republican Olympiad Committee', 'Olympiad', 'Science', 'In-person', current_date + 26, 'A staged olympiad in biology covering cells, genetics and ecology.', 'Grades 9-11. School-level biology.', 'https://example.org/apply/bio-olympiad', 9, 11, '{biology,olympiad,science,genetics}');
